# Generated by Django 5.2.12 on 2026-03-07 09:30

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('manufacturing_type', models.CharField(choices=[('3D_PRINTING', '3D Printing'), ('CNC_MACHINING', 'CNC Machining'), ('LASER_CUTTING', 'Laser Cutting')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('surface_area', models.FloatField(blank=True, null=True)),
                ('bounding_box_x', models.FloatField(blank=True, null=True)),
                ('bounding_box_y', models.FloatField(blank=True, null=True)),
                ('bounding_box_z', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
