# Generated by Django 4.2.19 on 2025-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('bsi', 'Bank Syariah Indonesia'), ('bjb', 'Bank Jabar Banten Syariah'), ('midtrans', 'Midtrans'), ('cash', 'Cash'), ('lainnya', 'Lainnya')], max_length=10),
        ),
    ]
