# Generated by Django 5.1.6 on 2026-03-04 08:21

import digital_products.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ebook', 'E-Book'), ('template', 'Template'), ('course', 'Online Course'), ('software', 'Software'), ('design', 'Design Asset'), ('music', 'Musik'), ('video', 'Video'), ('document', 'Dokumen'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=digital_products.models.digital_product_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('digital_link', models.URLField(help_text='Link produk digital (e.g., lynk.id, Google Drive, dll)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to=digital_products.models.digital_order_proof_path)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ocr_verified', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_orders', to=settings.AUTH_USER_MODEL)),
                ('digital_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='digital_products.digitalproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
