# Generated by Django 5.1.6 on 2026-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Gunakan TLS')),
                ('email_host_user', models.EmailField(help_text='Alamat email yang digunakan untuk mengirim (e.g., barakaheconomy@gmail.com)', max_length=254, verbose_name='Email Pengirim')),
                ('email_host_password', models.CharField(help_text='App Password Gmail (bukan password akun biasa). Buat di: Google Account > Security > 2-Step Verification > App Passwords', max_length=255, verbose_name='App Password')),
                ('sender_name', models.CharField(default='Barakah Economy', max_length=100, verbose_name='Nama Pengirim')),
            ],
            options={
                'verbose_name': 'Pengaturan Email',
                'verbose_name_plural': 'Pengaturan Email',
            },
        ),
    ]
