# Generated by Django 5.2.12 on 2026-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technology', models.CharField(choices=[('3D_PRINTING', '3D Printing'), ('CNC_MACHINING', 'CNC Machining'), ('LASER_CUTTING', 'Laser Cutting')], max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_volume', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_per_surface_area', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_per_weight', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('complexity_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('minimum_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('layer_height_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('infill_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('technology', 'material')},
            },
        ),
    ]
