# Generated by Django 4.2.19 on 2025-05-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('quiz', 'Quiz')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
        ),
    ]
