# Generated by Django 4.2.19 on 2025-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_enrollment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
