# Generated by Django 4.2.19 on 2025-05-30 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_coursematerial_alter_enrollment_user_delete_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='CourseEnrollment',
        ),
    ]
