# Generated by Django 4.2.19 on 2025-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseenrollment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
