# Generated by Django 4.2.19 on 2025-05-31 22:56

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseenrollment_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.proof_file_path),
        ),
    ]
