# Generated by Django 5.1.6 on 2026-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_coursematerial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='buyer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='buyer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
