# Generated by Django 5.1.6 on 2026-03-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courseenrollment_buyer_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
    ]
