# Generated by Django 5.1.6 on 2026-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courseenrollment_unique_together'),
    ]

    operations = [
        # Repair missing columns if any migration was interrupted/faked
        migrations.RunSQL(
            "ALTER TABLE courses_courseenrollment ADD COLUMN IF NOT EXISTS order_number varchar(30);"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_courseenrollment ADD COLUMN IF NOT EXISTS amount decimal(12,2) DEFAULT 0;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_courseenrollment ADD COLUMN IF NOT EXISTS buyer_email varchar(254) DEFAULT '';"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_courseenrollment ADD COLUMN IF NOT EXISTS buyer_name varchar(100) DEFAULT '';"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_courseenrollment ADD COLUMN IF NOT EXISTS buyer_phone varchar(20) DEFAULT '';"
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
