# Generated by Django 5.1.6 on 2026-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='shop_thumbnails/'),
        ),
    ]
