# Generated by Django 4.2.19 on 2025-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sembako', 'Bahan Makanan'), ('bumbu', 'Bumbu'), ('sayuran', 'Sayuran'), ('buah', 'Buah buahan'), ('protein', 'Bahan Protein'), ('mentahan', 'Bahan Makanan'), ('makan-minum', 'Makanan & Minuman'), ('obat', 'Produk Obat obatan'), ('herbal', 'Produk Herbal'), ('elektronik', 'Barang Elektronik'), ('peralatan', 'Peralatan Pertukangan'), ('pakaian', 'Pakaian'), ('asesoris', 'Asesoris'), ('perabotan', 'Perabotan Rumah'), ('kesehatan', 'Kesehatan'), ('kecantikan', 'Kecantikan'), ('kebersihan', 'Kebersihan'), ('perawatan', 'Perawatan'), ('kendaraan', 'Kendaraan'), ('rumah', 'Rumah'), ('gadget', 'Gadget'), ('lainnya', 'Lainnya')], max_length=20),
        ),
    ]
