# Generated by Django 4.2.19 on 2025-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_testimoni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimoni',
            old_name='title',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='testimoni',
            name='stars',
            field=models.IntegerField(default=5),
        ),
    ]
