# Generated by Django 5.2.12 on 2026-03-07 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_company', models.CharField(blank=True, max_length=255)),
                ('manufacturing_type', models.CharField(choices=[('3D_PRINTING', 'Cetak 3D'), ('CNC_MACHINING', 'CNC Machining'), ('LASER_CUTTING', 'Laser Cutting')], max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('QUOTE_SENT', 'Penawaran Dikirim'), ('ACCEPTED', 'Diterima Customer'), ('CONFIRMED', 'Dikonfirmasi Admin'), ('IN_PRODUCTION', 'Sedang Diproduksi'), ('QC_CHECK', 'Quality Control'), ('PACKING', 'Packing & Pengiriman'), ('SHIPPED', 'Telah Dikirim'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='QUOTE_SENT', max_length=20)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('update_type', models.CharField(choices=[('INFO', 'Informasi'), ('PROGRESS', 'Progress'), ('DELAY', 'Keterlambatan'), ('COMPLETED', 'Selesai'), ('ACTION_REQUIRED', 'Perlu Aksi')], default='INFO', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='order_updates/')),
                ('is_internal', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('FILE_CHECK', 'Pemeriksaan File'), ('MATERIAL_PREP', 'Persiapan Material'), ('SETUP', 'Setup Mesin'), ('PRODUCTION', 'Proses Produksi'), ('POST_PROCESS', 'Finishing'), ('QC', 'Quality Control'), ('PACKING', 'Packing')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('IN_PROGRESS', 'Berjalan'), ('COMPLETED', 'Selesai'), ('SKIPPED', 'Dilewati')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.order')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
