# Generated by Django 5.1.6 on 2025-11-26 04:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Not Active')], default=1)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('path', models.ImageField(db_column='path', upload_to='articles/')),
                ('article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='article.article')),
            ],
            options={
                'db_table': 'article_img',
            },
        ),
    ]
