# Generated by Django 5.1.6 on 2025-11-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20251126_1137'),
    ]

    operations = [
    ]
