# Generated by Django 5.1.6 on 2025-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_init_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='floating_url',
            field=models.URLField(blank=True, help_text='Masukkan URL lengkap (https://...) untuk tombol Floating Bubble', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
