# Generated by Django 5.1.6 on 2025-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_floating_url_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='floating_icon',
            field=models.ImageField(blank=True, help_text='Icon kecil di tombol bubble. Jika kosong, pakai icon default.', null=True, upload_to='bubble_icons/'),
        ),
        migrations.AddField(
            model_name='article',
            name='floating_label',
            field=models.CharField(blank=True, help_text="Teks pada tombol (misal: 'Beli Sekarang'). Default: Pesan Kalender", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='floating_url',
            field=models.URLField(blank=True, help_text='Link tujuan saat bubble diklik (misal: https://wa.me/...)', null=True),
        ),
    ]
